### ISSUE TITLE
Hint about ()

### ISSUE THREAD

**Issue by thomashines** [learn-co-curriculum/javascript-fix-the-scope-lab#12]
A hint can spark memory of previously learned knowledge, or it can prompt guessing through a particular inclination. In this case, the "A Hint about ()" text does not provide sufficient knowledge. It's also worth noting that the preceding entry on Closures does not provide specific syntactical knowledge to solve the Funky debug problem. 

I was able to solve this problem using the hint, eventually, but only in the most inefficient way, via trial and error. It would have been a much more valuable experience to draw upon knowledge to solve the debug problem. Trial-and-error, brute-force learning is exhausting and frustrating, particularly for students with limited schedules. Inventing requires more work than acquiring. 

It's also worth noting, I googled the problem externally, read a few external articles, and I still don't really understand the material or the solution in this context, rather, I'm kind of just shaking my head at the time I spent, not even knowing if my solution was best practices. I don't see a high value in learning this way. Acquiring and then apply knowledge is more efficient and more valuable.

**Comment by maxwellbenton** [comment]
Hi @thomashines, 

Thank you for providing this feedback. We've updated the instructions and tests in this lesson to include additional guidance and expanded the hint section to discuss using double parentheses, which should help future students to understand what is expected.

We apologize for any frustration this lab has caused, but we appreciate you taking the time to provide thorough feedback!
