### ISSUE TITLE
Bug with Run Local Tests

### ISSUE THREAD

**Issue by falgoonit** [learn-co-curriculum/javascript-fix-the-scope-lab#13]
Hello,

I have repeatedly run local tests using the Learn IDE console and have successfully submitted the lab. The system recognizes that the submit occurred however, the the system doesn't acknowledge that I have run local tests.

**Comment by aturkewi** [comment]
Hey @falgoonit it sounds like this might be more of an account issue than an issue with this specific lab. Are you still seeing this problem? If so, try out the Ask A Question button or the Report a Bug option to get a hand :)
