### ISSUE TITLE
Test case issues

### ISSUE THREAD

**Issue by grantlouisherman** [learn-co-curriculum/javascript-fix-the-scope-lab#14]
When I run the `learn` command, it keeps throwing me this error 

>  1) Fix the Scope myAnimal() returns my animal:                                
     TypeError: window.myAnimal is not a function                               
      at Context.it (test/index-test.js:6:21)   

For whatever reason the test cases are not identifying that `window."Function_Name"` is creditable. However, if I run it some other times the test cases do identify that `window."Function_Name"` is legitimate.

I even ran `npm install ` and it still did not work. Please advise.

**Comment by aturkewi** [comment]
Hey @grantlouisherman it's hard for me to identify the test case issue without knowing what code you had written at the time this error was being thrown.
I'm going to close this for now, but if you can post in the code here that was causing this area we can re-open it and take a look :)

Thanks for helping raise issues on Learn!
