### ISSUE TITLE
failing test

### ISSUE THREAD

**Issue by awatson31911** [learn-co-curriculum/javascript-fix-the-scope-lab#18]
Hi! Happy Sunday! 

My test for for "fix the scope" lab keeps failing. But I'm really not sure what's going wrong.

This is what I have:

var theFunk = funkyFunction();
console.log(theFunk()); ==> FUNKY!
console.log(theFunk() === "FUNKY!"); ==> true

Please help

**Comment by JessRudder** [comment]
Hi @awatson31911 if you're still having issues, please use the "Ask a Question" feature on the right side of Learn to get live help from a Learn Expert.
