### ISSUE TITLE
Hint is Not Helpful, Double ()() Needs Clarification In This Section or Previous Section.

### ISSUE THREAD

**Issue by jtxd4792** [learn-co-curriculum/javascript-fix-the-scope-lab#19]
This section needs to be re-written. I've found the lessons in Learn Co. extremely informative and helpful until now. I finally had to look in the issues section of this lab to figure out that the solution to to the final problem is var theFunk = funkyFunction()(). 

The hint is not helpful in the slightest, especially since in the previous section on scope there is no indication that function can be run with ()(). As a beginner to coding I never would have thought to use this as a solution, because I didn't know it was possible and especially since by all appearances double ()() appears to be improper syntax. I still don't understand why var theFunk = funkyFunction()() is a solution to the problem because this is not explained. I don't understand why we're given a convoluted explanation on scope and inner scope in the previous section along with a sprawling example, but are then expected to somehow discover on our own that var theFunk = funkyFunction()(), especially since running this code in the console with theFunk() provides us with the desired results of the test.

![screen shot 2017-04-05 at 1 02 51 pm](https://cloud.githubusercontent.com/assets/26720771/24717381/45b20212-1a00-11e7-9c0f-137dd64094aa.png)

Someone needs to fix this section up or explain this in the previous section. Forcing students to guess is not conducive to learning. You don't teach a kid math by explaining almost all the problems and purposefully leaving out an important concept. You give them the tools necessary and allow them to implement them on their own. We weren't given the necessary tools to complete the last portion of this lab.

**Comment by KALoftin** [comment]
I agree. I would have never figured that out if I didn't read this.

**Comment by bcwalk917** [comment]
I also agree. I actually have some limited coding experience but had no idea about this syntax and would've never figured it out if not for this post...I also tried "theFunk()" at one point and was extremely frustrated when it worked in the console but for some reason was still "wrong" in IDE.

**Comment by ElphC350** [comment]
I very much agree! Wow, thank you. I also NEVER would have thought of that even with the hint. I tried `var theFunk = funkyFunction(())` and I'd say that was pretty close, but never in a million years would have thought to put them side by side lol. I hope this comes to the attention of people that can remedy this!

**Comment by akshay1dhingra** [comment]
I agree... This concept itself is quite confusing to grasp... Do you have any suggestions on outside material that is good at explaining this further?

**Comment by asmijares1** [comment]
Just read this now. I never would have guessed that you should put ()() -- totally new concept to me.
I actually passed the test by modifying the test code itself  -- replaced theFunk with theFunk().

**Comment by gasganno** [comment]
I'll add my agreement as well. I went back through all the previous lessons/labs and couldn't find anything that would suggest this method for solving the problem. I've gotten stuck in the Swift course a couple of times with the same kind of issue. A small—but really significant—detail prevents completing the lesson. I think I'm pretty resourceful at searching online for solutions, but for what do you search when you don't know enough to know for what you should be searching?

**Comment by laconicsky** [comment]
I've just stumbled through this two years on from you guys.  Massively frustrating, only understood it by having one of the coaches online walk me through it.

**Comment by maxwellbenton** [comment]
Hi @jtxd4792,

Thank you for providing this feedback. We've updated the instructions and tests in this lesson to include additional guidance and expanded the hint section to discuss using double parentheses, which should help future students to understand what is expected.

We apologize for any frustration this lab has caused, but we appreciate you taking the time to provide thorough feedback!
