### ISSUE TITLE
learn.co, IDE conflict

### ISSUE THREAD

**Issue by anto10801** [learn-co-curriculum/javascript-fix-the-scope-lab#24]
Who do I contact for technical issues with this platform and the IDE? Previous challenge on learn.co, said I passed. IDE says I did not.

**Comment by maxwellbenton** [comment]
Hi @anto10801,

Sorry to hear you were having difficulties with Learn and the IDE. Although this may be a little late, if you do need any help regarding Learn or its related tools, please reach out to support@learn.co for further assistance.
