### ISSUE TITLE
Not making headway

### ISSUE THREAD

**Issue by tundeiness** [learn-co-curriculum/javascript-fix-the-scope-lab#25]
I think this task is a bit knotty and it has the ability to waste one's time if not careful. there is need to review the question to make it as plain as possble.

**Comment by maxwellbenton** [comment]
Hi @tundeiness,

Sorry to hear you were having trouble with this lab. We've recently updated the instructions and tests to provide better clarity and to help prevent this from happening to other students.

We apologize for any frustration this may have caused, but we appreciate you taking the time to provide us with feedback.

Thank you for contributing to a Learn lesson!
