### ISSUE TITLE
Test will not accept other solutions

### ISSUE THREAD

**Issue by DavidDoes** [learn-co-curriculum/javascript-fix-the-scope-lab#26]
This is the only solution this lab will take:
```
var funkyFunction = function() {
  return function() {
    return "FUNKY!"
  }
}

// We want to set theFunk equal to "FUNKY!" using our funkyFunction.
// NOTE: you only need to modify the code below this line.
var theFunk = funkyFunction();
theFunk = theFunk();
```

However, the following works as well, when run in console.
```
var funkyFunction = function() {
  return function() {
    return "FUNKY!"
  }
}

// We want to set theFunk equal to "FUNKY!" using our funkyFunction.
// NOTE: you only need to modify the code below this line.
var theFunk = funkyFunction();
theFunk(); //note this line
```

This second method works in the console, and is what the lesson teachers students to do. We've not yet addressed the method that is accepted by the test.

**Comment by asabogal** [comment]
yes! this issue is constantly brought up by several students in the lesson. 
This same question of why the test keeps failing with a correct code AND with the method we were taught in the lesson, keeps being raised.

suggest to update the lesson to include the double execution method, or to update the lab so that the code we are taught works out

**Comment by XCalybxr** [comment]
This lab will also take the solution,
var funkyFunction = function() {
  return function() {
    return "FUNKY!"
  }
}

// We want to set theFunk equal to "FUNKY!" using our funkyFunction.
// NOTE: you only need to modify the code below this line.
var theFunk = funkyFunction()(); //note this line, it's the response the hint is looking for and saves a line of code.

**Comment by andrew-lewell** [comment]
I've spent a good hour trying to figure out why my solution that should work is not passing the test! Very frustrating!

**Comment by maxwellbenton** [comment]
HI @DavidDoes,

We've updated this lab to include additional instructions and an expanded discussion on closures and using parentheses to call functions. While the second example is valid code, it isn't exactly what the tests are looking for. The additional instructions and guidance should help prevent this frustration for future students.

Thank you for contributing to a Learn lesson!
