### ISSUE TITLE
Learn submit: spontaneous error

### ISSUE THREAD

**Issue by malkhandos** [learn-co-curriculum/javascript-fix-the-scope-lab#27]
<<<<<<< HEAD
var theFunk = funkyFunction()()
=======
var theFunk = funkyFunction()
>>>>>>> 06d2c89200d21d1e436d1ac103258d416e0b0ed4

This bit of code seemed to show up out of nowhere.  I'm using two separate tabs and two monitors for labs.   The code passed the test on one monitor but failed when I submitted it on the second monitor.  When I reviewed what went wrong this strange code showed up.

**Comment by rrcobb** [comment]
This looks like the info that git adds to a file when it runs into a merge conflict. Under the hood, `learn submit` is using git to push your changes up to github. If there's a merge conflict, git will add lines like this to your file to indicate the differences between different versions. You can read more about merge conflicts here: https://imagej.net/Git_Conflicts
