### ISSUE TITLE
I am stuck passing the FUNKY test in this lab

### ISSUE THREAD

**Issue by amelad21** [learn-co-curriculum/javascript-fix-the-scope-lab#28]
Thank you in advance for your help

my code is like this; 
var theFunk = function funkyFunction('FUNKY!') {
  return theFunk
}
funkyFunction();
console.log(theFunk)

**Comment by XCalybxr** [comment]
I'm having trouble too but I'm thinking that everything we need we already have, we just need to append something to the end of our call to make it work... like this maybevar 
"theFunk = funkyFunction.**something**()?"  Still searching for answers.

var funkyFunction = function() {
  return function() {
    return "FUNKY!"
  }
}

// We want to set theFunk equal to "FUNKY!" using our funkyFunction.
// NOTE: you only need to modify the code below this line.
var theFunk = funkyFunction.**something**()

**Comment by XCalybxr** [comment]
Okay finally figured it out.  I'm sure I'm not allowed to give away answers here and don't want to do anything I'm not supposed to so here's a hint.  Think of the function call "FunkyFunction" as if you were moving to that directory.  and the command "( )" goes 1 directory deeper.  How might we go even deeper still?  Hope this helps and is not too much of a spoiler!

**Comment by maxwellbenton** [comment]
Hi @amelad21,

Sorry to hear you were having difficulty with this lab. We've updated the instructions and tests in this lab to provide better support and guidance for future students.
