### ISSUE TITLE
Beatles Loops lab error message 

### ISSUE THREAD

**Issue by SJeannie** [learn-co-curriculum/javascript-fix-the-scope-lab#29]
On the Beatles Loops lab, is it normal for me to get just this message as the error message? 

I type 'learn' and get only 1 error message, instead of multiple messages like other labs.  

Below is the error message I get: 

1)  "before all" hook:
     Error: Cannot find module 'jsdom/lib/old-api'
      at require (internal/module.js:11:18)
      at Context.<anonymous> (node_modules/mocha-jsdom/index.js:53:5)

Do I need to download some other package before being able to do this lab?

**Comment by maxwellbenton** [comment]
Hi @SJeannie,

Thank you for opening this issue. We were able to identify and resolve the cause of this problem in the package.json file dependencies. The Beatles Loops lab is now working as expected.

Thank you for this feedback and for contributing to a Learn lesson!
