### ISSUE TITLE
Last test needs to be called with ()

### ISSUE THREAD

**Issue by dowdje** [learn-co-curriculum/javascript-fix-the-scope-lab#7]
The test is being called as so:

  describe('theFunk', function() {
    it('is "FUNKY!"', function() {
      expect(window.theFunk.toEqual('FUNKY!'))
    })
  })

It wants theFunk to be called as a function so I think it needs to be theFunk(). Maybe I just did it wrong though.

**Comment by AnnJohn** [comment]
hi @dowdje this looks ok on our end. If you have specific questions about your code, please use Ask a Question and someone from our team will help your right away. Thanks!
