### ISSUE TITLE
Clarify Instructions to Cut Down on Questions

### ISSUE THREAD

**Issue by TheLucasMoore** [learn-co-curriculum/javascript-fix-the-scope-lab#8]
As a Learn Expert, we see about 3 questions each shift on this lab. It's unclear to students that the solution to the last test is `var theFunk = funkyFunction()()`. 

It would be useful to add the explanation as a hint within the README of this lab. I will make a PR right now with the proposed changes.

**Comment by TheLucasMoore** [comment]
@aturkewi @PeterBell We see this question come into expert chat all the time. I think this better clarifies the issue by explaining the use of `()` in a hint. Both Master and Solution are open PRs.

**Comment by thomashines** [comment]
I just completed this funky funk problem, and it still requires a solution outside the realm of knowledge, despite any previous attempts to fix it. It could be made adequate with some text in the curriculum showing this type of solution in action. As it is now, a student must still guess until the solution is invented. Invention, even partial invention, is a very inefficient mode of learning. Asking a student to guess tends to persuade that a topic is esoteric, unless every guess is correct. The goal here is to convey knowledge, not to evoke barriers to entry.
